/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hadoop_compression_snappy_SnappyDecompressor */

#ifndef _Included_com_hadoop_compression_snappy_SnappyDecompressor
#define _Included_com_hadoop_compression_snappy_SnappyDecompressor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_hadoop_compression_snappy_SnappyDecompressor_DEFAULT_DIRECT_BUFFER_SIZE
#define com_hadoop_compression_snappy_SnappyDecompressor_DEFAULT_DIRECT_BUFFER_SIZE 65536L
/*
 * Class:     com_hadoop_compression_snappy_SnappyDecompressor
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hadoop_compression_snappy_SnappyDecompressor_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_hadoop_compression_snappy_SnappyDecompressor
 * Method:    decompressBytesDirect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hadoop_compression_snappy_SnappyDecompressor_decompressBytesDirect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
