/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_compress_snappy_SnappyDecompressor */

#ifndef _Included_org_apache_hadoop_io_compress_snappy_SnappyDecompressor
#define _Included_org_apache_hadoop_io_compress_snappy_SnappyDecompressor
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_hadoop_io_compress_snappy_SnappyDecompressor_DEFAULT_DIRECT_BUFFER_SIZE
#define org_apache_hadoop_io_compress_snappy_SnappyDecompressor_DEFAULT_DIRECT_BUFFER_SIZE 65536L
/*
 * Class:     org_apache_hadoop_io_compress_snappy_SnappyDecompressor
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_compress_snappy_SnappyDecompressor_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_compress_snappy_SnappyDecompressor
 * Method:    decompressBytesDirect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_compress_snappy_SnappyDecompressor_decompressBytesDirect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
