/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_compress_snappy_SnappyCompressor */

#ifndef _Included_org_apache_hadoop_io_compress_snappy_SnappyCompressor
#define _Included_org_apache_hadoop_io_compress_snappy_SnappyCompressor
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_hadoop_io_compress_snappy_SnappyCompressor_DEFAULT_DIRECT_BUFFER_SIZE
#define org_apache_hadoop_io_compress_snappy_SnappyCompressor_DEFAULT_DIRECT_BUFFER_SIZE 65536L
/*
 * Class:     org_apache_hadoop_io_compress_snappy_SnappyCompressor
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_compress_snappy_SnappyCompressor_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_compress_snappy_SnappyCompressor
 * Method:    compressBytesDirect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_compress_snappy_SnappyCompressor_compressBytesDirect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
